Algoritmo "variaveis"


Var

	nome:caractere
  preco,media:real
  bandeira:logico

Inicio

escreval("Trabalhando com variáveis")
//atribuindo valores as variáveis
nome<-"Senac Largo Treze"
preco<-45.99
media<-(5.5+20.35)/2
bandeira<-verdadeiro
escreval("Seu nome é ",nome)
escreval("O produto custa ",preco)
escreval("Sua média é ",media)
escreval("Acesso ao sistema autorizado ",bandeira)

fimalgoritmo