Algoritmo "vetores"

Var

   idades: vetor [1..5] de inteiro
   nome: vetor [1..5] de caracter
   salario: vetor [1..5] de real
   status: vetor [1..5] de logico
Inicio

      //Inicializando as posições do vetor com valores inteiros
      idades[1]<-25
      idades[2]<-36
      idades[3]<-10
      idades[4]<-54
      idades[5]<-40
      
      //vetor de nomes
      nome[1]<-"Amarildo França"
      nome[2]<-"Reginaldo Leme"
      nome[3]<-"Maurício Nere"
      nome[4]<-"Gilberto Dimas"
      nome[5]<-"Urgano Mendes"
      //vetor de salario
      salario[1]<-1523.52
      salario[2]<-2325.25
      salario[3]<-1634.53
      salario[4]<-2852.75
      salario[5]<-2658.85
      //vetor lógico
      status[1]<-verdadeiro
      status[2]<-falso
      status[3]<-falso
      status[4]<-verdadeiro
      status[5]<-falso

      
      
      escreval("A sua idade: ", idades[1]," anos")
      escreval("A sua idade: ", idades[2]," anos")
      escreval("A sua idade: ", idades[3]," anos")
      escreval("A sua idade: ", idades[4]," anos")
      escreval("A sua idade: ", idades[5]," anos")
      
      escreval("Seu nome é : ", nome[1])
      escreval("Seu nome é : ", nome[2])
      escreval("Seu nome é : ", nome[3])
      escreval("Seu nome é : ", nome[4])
      escreval("Seu nome é : ", nome[5])

      escreval("Seu salário: ", salario[1])
      escreval("Seu salário: ", salario[2])
      escreval("Seu salário: ", salario[3])
      escreval("Seu salário: ", salario[4])
      escreval("Seu salário: ", salario[5])

      
      escreval("Acessou o sistema: ", status[1])
      escreval("Acessou o sistema: ", status[2])
      escreval("Acessou o sistema: ", status[3])
      escreval("Acessou o sistema: ", status[4])
      escreval("Acessou o sistema: ", status[5])


Fimalgoritmo